webtalk_init -webtalk_dir C:\\Users\\nate\\439MP3Accelerator\\MP3Accelerator\\MP3Accelerator.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 29 13:04:05 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "jjuinssc33ksege4o91t0tk0s1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1511989089562" -context "sdk\\\\bsp/1511989089562"
webtalk_add_data -client sdk -key hwid -value "1510851481004" -context "sdk\\\\bsp/1511989089562"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1511989089562"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1511989089562"
webtalk_transmit -clientid 2118185188 -regid "" -xml C:\\Users\\nate\\439MP3Accelerator\\MP3Accelerator\\MP3Accelerator.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\nate\\439MP3Accelerator\\MP3Accelerator\\MP3Accelerator.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\nate\\439MP3Accelerator\\MP3Accelerator\\MP3Accelerator.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
