webtalk_init -webtalk_dir C:\\Xilinx\\projects\\CPE439\\MP3Project\\MP3Accelerator\\MP3Accelerator.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2017-11-29 14:54:16" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210778909_1777507066_210600704_261" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e5809r8hi5kb5hgfg9qh8arda0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_14" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2295 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1511995590700" -context "sdk\\\\bsp/1511995590700"
webtalk_add_data -client sdk -key hwid -value "1511885827770" -context "sdk\\\\bsp/1511995590700"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1511995590700"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1511995590700"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1511995590700"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1511996056736"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1511996056736"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1511996056736"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1511996056736"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1511996056736"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1511996056736"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1511996056736"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1511996056736"
webtalk_transmit -clientid 1437243910 -regid "210778909_1777507066_210600704_261" -xml C:\\Xilinx\\projects\\CPE439\\MP3Project\\MP3Accelerator\\MP3Accelerator.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Xilinx\\projects\\CPE439\\MP3Project\\MP3Accelerator\\MP3Accelerator.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Xilinx\\projects\\CPE439\\MP3Project\\MP3Accelerator\\MP3Accelerator.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
